export const entryQueue9v9 = {
  config: {
    teamCount: 2,
    classes: [
      { name: 'scout', count: 1 },
      { name: 'soldier', count: 1 },
      { name: 'pyro', count: 1 },
      { name: 'demoman', count: 1 },
      { name: 'heavy', count: 1 },
      { name: 'engineer', count: 1 },
      { name: 'medic', count: 1 },
      { name: 'sniper', count: 1 },
      { name: 'spy', count: 1 },
    ],
  },
  slots: [
    { id: 0, gameClass: 'scout', ready: false },
    { id: 1, gameClass: 'scout', ready: false },
    { id: 2, gameClass: 'soldier', ready: false },
    { id: 3, gameClass: 'soldier', ready: false },
    { id: 4, gameClass: 'pyro', ready: false },
    { id: 5, gameClass: 'pyro', ready: false },
    { id: 6, gameClass: 'demoman', ready: false },
    { id: 7, gameClass: 'demoman', ready: false },
    { id: 8, gameClass: 'heavy', ready: false },
    { id: 9, gameClass: 'heavy', ready: false },
    { id: 10, gameClass: 'engineer', ready: false },
    { id: 11, gameClass: 'engineer', ready: false },
    { id: 12, gameClass: 'medic', ready: false },
    { id: 13, gameClass: 'medic', ready: false },
    { id: 14, gameClass: 'sniper', ready: false },
    { id: 15, gameClass: 'sniper', ready: false },
    { id: 16, gameClass: 'spy', ready: false },
    { id: 17, gameClass: 'spy', ready: false },
  ],
};
